FROM python:3.12-slim
WORKDIR /app
COPY services/user/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY services/user/main.py .
EXPOSE 8082
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8082"]
